<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>io.entgra.proprietary</groupId>
        <artifactId>alert-mgt</artifactId>
        <version>1.0.0-SNAPSHOT</version>
    </parent>

    <artifactId>io.entgra.proprietary.alert.mgt.common</artifactId>
    <packaging>bundle</packaging>
    <name>Entgra IoT - Alert Mgt Common</name>
    <description>Entgra IoT - Alert Mgt Common</description>
    <url>http://entgra.io</url>



    <properties>
        <maven.compiler.source>11</maven.compiler.source>
        <maven.compiler.target>11</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
            </plugin>
            <plugin>
                <groupId>org.apache.felix</groupId>
                <artifactId>maven-scr-plugin</artifactId>
            </plugin>
            <plugin>
                <groupId>org.apache.felix</groupId>
                <artifactId>maven-bundle-plugin</artifactId>
                <version>5.1.8</version>
                <extensions>true</extensions>
                <configuration>
                    <instructions>
                        <Bundle-SymbolicName>${project.artifactId}</Bundle-SymbolicName>
                        <Bundle-Name>${project.artifactId}</Bundle-Name>
                        <Bundle-Version>${io.entgra.proprietary.alert.mgt.version}</Bundle-Version>
                        <Bundle-Description>Alert Management Common Bundle</Bundle-Description>
                        <Import-Package>
                            javax.xml.bind.annotation; version="${javax.xml.bind.imp.pkg.version}"
                        </Import-Package>
                        <Export-Package>
                            io.entgra.proprietary.alert.mgt.common.*
                        </Export-Package>
                    </instructions>
                </configuration>
            </plugin>
        </plugins>
    </build>


</project>
