<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>io.entgra.alert.mgt</groupId>
        <artifactId>alert-mgt</artifactId>
        <version>1.0.0-SNAPSHOT</version>
    </parent>

    <artifactId>io.entgra.alert.mgt.core</artifactId>
    <packaging>bundle</packaging>

    <properties>
        <maven.compiler.source>11</maven.compiler.source>
        <maven.compiler.target>11</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>

    <build>
        <plugins>
            <plugin>
                <groupId>org.jacoco</groupId>
                <artifactId>jacoco-maven-plugin</artifactId>
                <version>0.8.10</version>
                <executions>
                    <execution>
                        <goals>
                            <goal>prepare-agent</goal>
                        </goals>
                    </execution>
                    <execution>
                        <id>report</id>
                        <phase>verify</phase>
                        <goals>
                            <goal>report</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.apache.felix</groupId>
                <artifactId>maven-bundle-plugin</artifactId>
                <version>5.1.8</version>
                <extensions>true</extensions>
                <configuration>
                    <instructions>
                        <Bundle-SymbolicName>${project.artifactId}</Bundle-SymbolicName>
                        <Bundle-Name>${project.artifactId}</Bundle-Name>
                        <Bundle-Version>${io.entgra.alert.mgt.version}</Bundle-Version>
                        <Bundle-Description>Alert Management Core</Bundle-Description>
                        <Private-Package>io.entgra.alert.mgt.core.internal</Private-Package>
                        <Import-Package>
                            io.entgra.alert.mgt.common;version="${io.entgra.alert.mgt.version}",
                            io.entgra.alert.mgt.common.spi;version="${io.entgra.alert.mgt.version}",
                            io.entgra.alert.mgt.common.exception;version="${io.entgra.alert.mgt.version}",
                            io.entgra.alert.mgt.common.beans;version="${io.entgra.alert.mgt.version}",
                            org.osgi.service.component;version="${imp.package.version.osgi.service}",

                            org.apache.commons.lang;version="[2.6,3)",
                            org.apache.commons.logging;version="[1.2,2)",
                        </Import-Package>
                        <Export-Package>
                            !io.entgra.alert.mgt.core.internal,
                            io.entgra.alert.mgt.core.*
                        </Export-Package>
                    </instructions>
                </configuration>
            </plugin>
        </plugins>
    </build>

    <dependencies>
        <dependency>
            <groupId>io.entgra.alert.mgt</groupId>
            <artifactId>io.entgra.alert.mgt.common</artifactId>
        </dependency>
        <dependency>
            <groupId>commons-logging</groupId>
            <artifactId>commons-logging</artifactId>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>org.eclipse.osgi</groupId>
            <artifactId>org.eclipse.osgi</artifactId>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>org.eclipse.osgi</groupId>
            <artifactId>org.eclipse.osgi.services</artifactId>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>org.apache.cxf</groupId>
            <artifactId>cxf-rt-frontend-jaxws</artifactId>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>org.apache.cxf</groupId>
            <artifactId>cxf-rt-frontend-jaxrs</artifactId>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>org.apache.cxf</groupId>
            <artifactId>cxf-rt-transports-http</artifactId>
            <scope>provided</scope>
        </dependency>
    </dependencies>
</project>