<?org.wso2.uesxml version="1.0" encoding="UTF-8"?>

<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">

    <parent>
        <groupId>io.entgra.facility.monitor</groupId>
        <artifactId>product-facility-monitor</artifactId>
        <version>1.0.0-SNAPSHOT</version>
        <relativePath>../../pom.xml</relativePath>
    </parent>

    <modelVersion>4.0.0</modelVersion>
    <artifactId>facility-monitor-p2-profile</artifactId>
    <packaging>pom</packaging>
    <name>Entgra Facility Monitor - p2 profile</name>
    <description>Entgra Facility Monitor p2 profile</description>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-dependency-plugin</artifactId>
                <inherited>false</inherited>
                <executions>
                    <execution>
                        <id>1-unpack-entgra-iots</id>
                        <phase>test</phase>
                        <goals>
                            <goal>unpack</goal>
                        </goals>
                        <configuration>
                            <artifactItems>
                                <artifactItem>
                                    <groupId>io.entgra.proprietary.product.iots</groupId>
                                    <artifactId>io.entgra.proprietary.product.iots.distribution-pro-iot</artifactId>s
                                    <type>zip</type>
                                    <overWrite>true</overWrite>
                                    <outputDirectory>target</outputDirectory>
                                </artifactItem>
                            </artifactItems>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
<!--            <plugin>-->
<!--                <groupId>org.wso2.maven</groupId>-->
<!--                <artifactId>carbon-p2-plugin</artifactId>-->
<!--                <version>5.1.2</version>-->
<!--                <executions>-->
<!--                    <execution>-->
<!--                        <id>2-p2-repo-generation</id>-->
<!--                        <phase>package</phase>-->
<!--                        <goals>-->
<!--                            <goal>p2-repo-gen</goal>-->
<!--                        </goals>-->
<!--                        <configuration>-->
<!--                            <metadataRepository>file:${project.build.directory}/p2-repo</metadataRepository>-->
<!--                            <artifactRepository>file:${project.build.directory}/p2-repo</artifactRepository>-->
<!--                            <publishArtifacts>true</publishArtifacts>-->
<!--                            <publishArtifactRepository>true</publishArtifactRepository>-->
<!--                            <featureArtifacts>-->
<!--                                <featureArtifactDef>-->
<!--                                    io.entgra:io.entgra.device.mgt.iot.power.meter.feature:${io.entgra.alert.mgt.version}-->
<!--                                </featureArtifactDef>-->
<!--                                <featureArtifactDef>-->
<!--                                    io.entgra:io.entgra.meter.request.feature:${io.entgra.alert.mgt.version}-->
<!--                                </featureArtifactDef>-->
<!--                                <featureArtifactDef>-->
<!--                                    io.entgra:io.entgra.branch.mgt.feature:${io.entgra.alert.mgt.version}-->
<!--                                </featureArtifactDef>-->
<!--                            </featureArtifacts>-->
<!--                        </configuration>-->
<!--                    </execution>-->
<!--                    <execution>-->
<!--                        <id>feature-install</id>-->
<!--                        <phase>package</phase>-->
<!--                        <goals>-->
<!--                            <goal>p2-profile-gen</goal>-->
<!--                        </goals>-->
<!--                        <configuration>-->
<!--                            <profile>default</profile>-->
<!--                            <metadataRepository>file:${project.build.directory}/p2-repo</metadataRepository>-->
<!--                            <artifactRepository>file:${project.build.directory}/p2-repo</artifactRepository>-->
<!--                            <destination>${project.build.directory}/${entgra-iot-pro}/repository/components</destination>-->
<!--                            <deleteOldProfileFiles>true</deleteOldProfileFiles>-->
<!--                            <features>-->
<!--                                <feature>-->
<!--                                    <id>io.entgra.device.mgt.iot.power.meter.feature.group</id>-->
<!--                                    <version>${power.meter.core.version}</version>-->
<!--                                </feature>-->
<!--                                <feature>-->
<!--                                    <id>io.entgra.meter.request.feature.group</id>-->
<!--                                    <version>${power.meter.core.version}</version>-->
<!--                                </feature>-->
<!--                                <feature>-->
<!--                                    <id>io.entgra.branch.mgt.feature.group</id>-->
<!--                                    <version>${power.meter.core.version}</version>-->
<!--                                </feature>-->
<!--                            </features>-->
<!--                        </configuration>-->
<!--                    </execution>-->
<!--                </executions>-->
<!--            </plugin>-->
            <plugin>
                <groupId>com.google.code.maven-replacer-plugin</groupId>
                <artifactId>replacer</artifactId>
                <version>1.5.3</version>
                <executions>
                    <execution>
                        <id>update-bundles</id>
                        <phase>package</phase>
                        <goals>
                            <goal>replace</goal>
                        </goals>
                        <configuration>
                            <file>
                                ${project.build.directory}/${entgra-iot-pro}/repository/components/default/configuration/org.eclipse.equinox.simpleconfigurator/bundles.info
                            </file>
                            <replacements>
                                <replacement>
                                    <token>false</token>
                                    <value>true</value>
                                </replacement>
                            </replacements>
                        </configuration>
                    </execution>
<!--                    <execution>-->
<!--                        <id>set-meter-db-for-sims-device-type</id>-->
<!--                        <phase>package</phase>-->
<!--                        <goals>-->
<!--                            <goal>replace</goal>-->
<!--                        </goals>-->
<!--                        <configuration>-->
<!--                            <file>${project.build.directory}/${entgra-iot-pro}/repository/deployment/server/devicetypes/sim.xml</file>-->
<!--                            <replacements>-->
<!--                                <replacement>-->
<!--                                    <token>SimMgt_DS</token>-->
<!--                                    <value>SmartGrid_DS</value>-->
<!--                                </replacement>-->
<!--                            </replacements>-->
<!--                        </configuration>-->
<!--                    </execution>-->
<!--                    <execution>-->
<!--                        <id>set-meter-db-for-sims-config</id>-->
<!--                        <phase>package</phase>-->
<!--                        <goals>-->
<!--                            <goal>replace</goal>-->
<!--                        </goals>-->
<!--                        <configuration>-->
<!--                            <file>${project.build.directory}/${entgra-iot-pro}/repository/conf/sim-mgt-dbconfig.xml</file>-->
<!--                            <replacements>-->
<!--                                <replacement>-->
<!--                                    <token>SimMgt_DS</token>-->
<!--                                    <value>SmartGrid_DS</value>-->
<!--                                </replacement>-->
<!--                            </replacements>-->
<!--                        </configuration>-->
<!--                    </execution>-->
                </executions>
            </plugin>
        </plugins>
    </build>

</project>
